require 'active_record'
require_relative 'active_record/notification.rb'
require_relative 'active_record/adapter.rb'
require_relative 'active_record/activist.rb'
require_relative 'active_record/notifiable.rb'
require_relative 'active_record/notifying.rb'
